// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/gen_ui_types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Boot-order invariant, step 1: open the embedded SurrealDB store (config +
/// memory/graph-RAG both live in it on mobile — see gen_ui_agent::state::init's
/// doc comment on why memory is SurrealDB-only regardless of platform) and
/// initialise gen_ui_agent's process-lifetime state. Idempotent per process.
Future<void> runMigrations({required String dataDir}) =>
    GenUiCore.instance.api.crateApiBootRunMigrations(dataDir: dataDir);

/// Boot-order invariant, step 2: seed data. No seed bundles for the PoC yet
/// (C-104's curated corpus lands separately) — a real no-op until then.
Future<void> loadSeeds() => GenUiCore.instance.api.crateApiBootLoadSeeds();

/// Boot-order invariant, step 3: attach sync shapes. C-106's job — real no-op
/// until then (migrations+seeds must still run first even without live sync).
Future<void> attachSyncShapes() =>
    GenUiCore.instance.api.crateApiBootAttachSyncShapes();
