// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/gen_ui_types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Boot-order invariant, step 1: open the embedded SurrealDB store (config +
/// memory/graph-RAG both live in it on mobile — see gen_ui_agent::state::init's
/// doc comment on why memory is SurrealDB-only regardless of platform) and
/// initialise gen_ui_agent's process-lifetime state. Idempotent per process.
Future<void> runMigrations({required String dataDir}) =>
    GenUiCore.instance.api.crateApiBootRunMigrations(dataDir: dataDir);

/// Boot-order invariant, step 2: seed data.
///
/// Ingests the C-111 demo corpus through the SAME `gen_ui_agent::memory` the desktop
/// plugin's `load_seeds` calls — no duplicated seeding logic, and both surfaces get an
/// identical corpus. Idempotent (stable seed ids), so running on every start upserts
/// rather than duplicates. MUST follow `run_migrations`.
///
/// Returns the number of notes seeded, so Dart can report progress rather than stare at
/// a silent pause: every note is embedded here, which is not instant on a cold start.
Future<int> loadSeeds() => GenUiCore.instance.api.crateApiBootLoadSeeds();

/// Boot-order invariant, step 3: attach sync (C-106).
///
/// **Still a no-op on mobile, and deliberately so — see below.** Desktop's equivalent
/// (`tauri-plugin-gen-ui::commands::attach_sync_shapes`) is live: it starts an
/// `FrfSyncTransport` whose read lane materialises row changes into `PgLocalStore`.
///
/// Mobile cannot reuse that, because mobile has no Postgres. `run_migrations` above
/// opens embedded SurrealDB and registers it as BOTH config and memory backend
/// (`ConfigBackend::Surreal`) — pglite-oxide is structurally unsupported on iOS/Android
/// (no child processes, no JIT), which is why the split exists at all. So the read lane
/// needs a `LocalStore` over SurrealDB, and `gen_ui_db_graph`'s public surface is
/// intent-level by design ("INTENT-LEVEL, never raw SurrealQL" — lib.rs): it exposes
/// `memory_ingest`/`memory_search`/`graph_expand`, not row upserts. Writing a
/// `SurrealLocalStore` means adding a row-persistence surface to that crate, which is a
/// real design decision about its contract — not something to smuggle in under a sync
/// task. Tracked as C-106 T5; the honest state is "desktop syncs, mobile does not yet".
///
/// The write path is NOT blocked by this: `gen_ui_agent::sync_sink::forge_write_sink`
/// is platform-agnostic, so once a mobile `LocalStore` exists the wiring here mirrors
/// desktop's exactly.
Future<void> attachSyncShapes() =>
    GenUiCore.instance.api.crateApiBootAttachSyncShapes();
