// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Start a chat turn; returns the run_id whose events arrive on chat_events(run_id).
/// `thread_id` is reserved for multi-thread history (not yet used — the agent
/// layer takes the full turn history via `message` for now).
Future<CoreResultString> chatSend({
  required String threadId,
  required String message,
}) =>
    GenUiCore.instance.api
        .crateApiChatChatSend(threadId: threadId, message: message);

/// Hybrid memory search (vector recall + graph expansion + BM25, RRF-fused in Rust).
/// Returns opaque JSON rows the UI renders as Memory/Citation ContentBlocks.
Future<CoreResultVecString> memorySearch({
  required String query,
  required int k,
}) =>
    GenUiCore.instance.api.crateApiChatMemorySearch(query: query, k: k);

/// Expand the entity graph around a node to a given depth. Intent-level; the
/// recursive RELATE traversal lives in gen_ui_db::graph (C-004).
Future<CoreResultVecString> graphExpand({
  required String entityId,
  required int depth,
}) =>
    GenUiCore.instance.api
        .crateApiChatGraphExpand(entityId: entityId, depth: depth);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoreResult < String >>>
abstract class CoreResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoreResult < Vec < String > >>>
abstract class CoreResultVecString implements RustOpaqueInterface {}
