// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/gen_ui_db_graph.dart';
import '../third_party/gen_ui_types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Start a chat turn; returns the run_id whose events arrive on chat_events(run_id).
/// `messages` is the selected conversation's role/text history. The thread id
/// remains transport metadata; persistence is owned by the entity repository.
Future<String> chatSend(
        {required String threadId,
        required String message,
        required List<String> messages}) =>
    GenUiCore.instance.api.crateApiChatChatSend(
        threadId: threadId, message: message, messages: messages);

/// Ingest a note into memory (embeds on-device via fastembed, upserts into
/// SurrealDB). Returns the assigned record id.
Future<String> memoryIngest({required String text}) =>
    GenUiCore.instance.api.crateApiChatMemoryIngest(text: text);

/// Hybrid memory search (vector recall + graph expansion + BM25, RRF-fused in Rust).
Future<List<MemoryHit>> memorySearch({required String query, required int k}) =>
    GenUiCore.instance.api.crateApiChatMemorySearch(query: query, k: k);

/// Expand the entity graph around a node to a given depth.
Future<List<RelatedEntity>> graphExpand(
        {required String entityId, required int depth}) =>
    GenUiCore.instance.api
        .crateApiChatGraphExpand(entityId: entityId, depth: depth);
