// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/gen_ui_types/error.dart';
import '../third_party/gen_ui_types/transport.dart';
import '../third_party/gen_ui_types/view.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// List entities matching a view (filters/sorts/pagination compiled to SQL in Rust).
Future<ListResult> entityList({required ViewDescriptor view}) =>
    GenUiCore.instance.api.crateApiEntityEntityList(view: view);

/// Fetch one entity by type + id.
Future<EntityRecord?> entityGet(
        {required String entityType, required String id}) =>
    GenUiCore.instance.api
        .crateApiEntityEntityGet(entityType: entityType, id: id);

/// Create an entity. Emits a ChangeEvent::Upsert on the entity_changes stream.
Future<EntityRecord> entityCreate({required EntityRecord record}) =>
    GenUiCore.instance.api.crateApiEntityEntityCreate(record: record);

/// Update an entity. Emits a ChangeEvent::Upsert.
Future<EntityRecord> entityUpdate({required EntityRecord record}) =>
    GenUiCore.instance.api.crateApiEntityEntityUpdate(record: record);

/// Delete an entity. Emits a ChangeEvent::Delete.
Future<void> entityDelete({required String entityType, required String id}) =>
    GenUiCore.instance.api
        .crateApiEntityEntityDelete(entityType: entityType, id: id);
