// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/gen_ui_types/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `slot`

/// Start a microphone recording. Errors if one is already in progress.
Future<void> scribeStart() =>
    GenUiCore.instance.api.crateApiScribeScribeStart();

/// Stop the in-flight recording and transcribe it on-device. Returns the
/// transcript; the caller (Dart UI) decides whether/how to save it to memory.
Future<String> scribeStop() =>
    GenUiCore.instance.api.crateApiScribeScribeStop();
