// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Subscribe to the A2UI event stream for a chat run. The core produces
/// ContentBlock-bearing events; the transport layer (`@flint/react`, flint_genui)
/// is bypassed by contract.
///
/// The broadcast is process-wide, not per-run (only `RunStarted`/`RunFinished`
/// carry a `run_id`; `Block` does not) — correct for this PoC's single-turn-at-
/// a-time chat, since only one run is ever in flight. Multiplexing by run_id is
/// a real gap for concurrent turns, deferred until that's an actual requirement.
Stream<A2UiEvent> chatEvents({required String runId}) =>
    GenUiCore.instance.api.crateApiStreamsChatEvents(runId: runId);

/// Subscribe to entity change events. One Dart listener fans these into
/// `ref.invalidate` calls per the PEM-Flutter cascade-invalidation design.
Stream<ChangeEvent> entityChanges() =>
    GenUiCore.instance.api.crateApiStreamsEntityChanges();

/// Subscribe to the sync status feed that drives the UI sync chip.
Stream<SyncStatus> syncStatus() =>
    GenUiCore.instance.api.crateApiStreamsSyncStatus();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<A2uiEvent>>
abstract class A2UiEvent implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChangeEvent>>
abstract class ChangeEvent implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncStatus>>
abstract class SyncStatus implements RustOpaqueInterface {}
