// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Subscribe to the A2UI event stream for a chat run. The core produces
/// ContentBlock-bearing events, serialized to JSON (see module doc for why);
/// the transport layer (`@flint/react`, flint_genui) is bypassed by contract.
///
/// Subscribes to gen_ui_agent's per-run broadcast channel (registered by
/// `chat::chat_send` before it returns the run_id) and forwards every event,
/// JSON-encoded, into the frb `StreamSink` until the run's producer task
/// closes the channel (terminal `RunFinished`/`RunError`, after which
/// `RunRegistry::remove` drops the sender). If `run_id` is unknown (never
/// started, or already finished before this subscription attached), the sink
/// is dropped immediately — there is nothing to stream. A serialization
/// failure (should be unreachable — `A2uiEvent` is `Serialize`-derived with
/// no non-serializable fields) is logged and the event is skipped rather than
/// panicking the forwarder task.
Stream<String> chatEvents({required String runId}) =>
    GenUiCore.instance.api.crateApiStreamsChatEvents(runId: runId);

/// Subscribe to entity change events. One Dart listener fans these into
/// `ref.invalidate` calls per the PEM-Flutter cascade-invalidation design.
Stream<ChangeEvent> entityChanges() =>
    GenUiCore.instance.api.crateApiStreamsEntityChanges();

/// Subscribe to the sync status feed that drives the UI sync chip.
Stream<SyncStatus> syncStatus() =>
    GenUiCore.instance.api.crateApiStreamsSyncStatus();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChangeEvent>>
abstract class ChangeEvent implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncStatus>>
abstract class SyncStatus implements RustOpaqueInterface {}
