// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chat.dart';
import 'api/entity.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class GenUiCore
    extends BaseEntrypoint<GenUiCoreApi, GenUiCoreApiImpl, GenUiCoreWire> {
  @internal
  static final instance = GenUiCore._();

  GenUiCore._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    GenUiCoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required GenUiCoreApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<GenUiCoreApiImpl, GenUiCoreWire> get apiImplConstructor =>
      GenUiCoreApiImpl.new;

  @override
  WireConstructor<GenUiCoreWire> get wireConstructor =>
      GenUiCoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitCore();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1610600774;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'gen_ui_ffi',
    ioDirectory: '../rust/crates/gen_ui_ffi/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class GenUiCoreApi extends BaseApi {
  Future<CoreResultString> crateApiChatChatSend({
    required String threadId,
    required String message,
  });

  Future<CoreResultEntityRecord> crateApiEntityEntityCreate({
    required EntityRecord record,
  });

  Future<CoreResult> crateApiEntityEntityDelete({
    required String entityType,
    required String id,
  });

  Future<CoreResultOptionEntityRecord> crateApiEntityEntityGet({
    required String entityType,
    required String id,
  });

  Future<CoreResultListResult> crateApiEntityEntityList({
    required ViewDescriptor view,
  });

  Future<CoreResultEntityRecord> crateApiEntityEntityUpdate({
    required EntityRecord record,
  });

  Future<CoreResultVecString> crateApiChatGraphExpand({
    required String entityId,
    required int depth,
  });

  Future<void> crateApiInitCore({BigInt? workerThreads});

  Future<CoreResultVecString> crateApiChatMemorySearch({
    required String query,
    required int k,
  });

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResult;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResult;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CoreResultPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultEntityRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CoreResultEntityRecordPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultListResult;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultListResult;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CoreResultListResultPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultOptionEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultOptionEntityRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CoreResultOptionEntityRecordPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultString;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultString;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CoreResultStringPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultVecString;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultVecString;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CoreResultVecStringPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_EntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_EntityRecord;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_EntityRecordPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ViewDescriptor;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ViewDescriptor;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ViewDescriptorPtr;
}

class GenUiCoreApiImpl extends GenUiCoreApiImplPlatform
    implements GenUiCoreApi {
  GenUiCoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<CoreResultString> crateApiChatChatSend({
    required String threadId,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(threadId, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatChatSendConstMeta,
        argValues: [threadId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatSendConstMeta => const TaskConstMeta(
        debugName: 'chat_send',
        argNames: ['threadId', 'message'],
      );

  @override
  Future<CoreResultEntityRecord> crateApiEntityEntityCreate({
    required EntityRecord record,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
            record,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityCreateConstMeta,
        argValues: [record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityCreateConstMeta =>
      const TaskConstMeta(debugName: 'entity_create', argNames: ['record']);

  @override
  Future<CoreResult> crateApiEntityEntityDelete({
    required String entityType,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityType, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityDeleteConstMeta,
        argValues: [entityType, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityDeleteConstMeta => const TaskConstMeta(
        debugName: 'entity_delete',
        argNames: ['entityType', 'id'],
      );

  @override
  Future<CoreResultOptionEntityRecord> crateApiEntityEntityGet({
    required String entityType,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityType, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityGetConstMeta,
        argValues: [entityType, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityGetConstMeta => const TaskConstMeta(
        debugName: 'entity_get',
        argNames: ['entityType', 'id'],
      );

  @override
  Future<CoreResultListResult> crateApiEntityEntityList({
    required ViewDescriptor view,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
            view,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityListConstMeta,
        argValues: [view],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityListConstMeta =>
      const TaskConstMeta(debugName: 'entity_list', argNames: ['view']);

  @override
  Future<CoreResultEntityRecord> crateApiEntityEntityUpdate({
    required EntityRecord record,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
            record,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityUpdateConstMeta,
        argValues: [record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityUpdateConstMeta =>
      const TaskConstMeta(debugName: 'entity_update', argNames: ['record']);

  @override
  Future<CoreResultVecString> crateApiChatGraphExpand({
    required String entityId,
    required int depth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityId, serializer);
          sse_encode_u_32(depth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatGraphExpandConstMeta,
        argValues: [entityId, depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatGraphExpandConstMeta => const TaskConstMeta(
        debugName: 'graph_expand',
        argNames: ['entityId', 'depth'],
      );

  @override
  Future<void> crateApiInitCore({BigInt? workerThreads}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_usize(workerThreads, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitCoreConstMeta,
        argValues: [workerThreads],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitCoreConstMeta =>
      const TaskConstMeta(debugName: 'init_core', argNames: ['workerThreads']);

  @override
  Future<CoreResultVecString> crateApiChatMemorySearch({
    required String query,
    required int k,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(k, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatMemorySearchConstMeta,
        argValues: [query, k],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatMemorySearchConstMeta =>
      const TaskConstMeta(debugName: 'memory_search', argNames: ['query', 'k']);

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResult => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResult => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultEntityRecord => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultEntityRecord => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultListResult => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultListResult => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultOptionEntityRecord => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultOptionEntityRecord => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultString => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultString => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultVecString => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultVecString => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_EntityRecord => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_EntityRecord => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ViewDescriptor => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ViewDescriptor => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor;

  @protected
  CoreResult
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultEntityRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultEntityRecordImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  CoreResultListResult
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultListResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultOptionEntityRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultOptionEntityRecordImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  CoreResultString
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultVecString
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultVecStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EntityRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EntityRecordImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ViewDescriptor
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ViewDescriptorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResult
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultEntityRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultEntityRecordImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  CoreResultListResult
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultListResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultOptionEntityRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultOptionEntityRecordImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  CoreResultString
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultVecString
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultVecStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EntityRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EntityRecordImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ViewDescriptor
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ViewDescriptorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CoreResult
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultEntityRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultEntityRecordImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultListResult
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultListResultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultOptionEntityRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultOptionEntityRecordImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultString
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultVecString
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultVecStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EntityRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EntityRecordImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ViewDescriptor
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ViewDescriptorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResult
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultEntityRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultEntityRecordImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultListResult
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultListResultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultOptionEntityRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultOptionEntityRecordImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultString
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreResultVecString
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultVecStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EntityRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EntityRecordImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ViewDescriptor
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ViewDescriptorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
    CoreResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
    CoreResultEntityRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultEntityRecordImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
    CoreResultListResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultListResultImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
    CoreResultOptionEntityRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultOptionEntityRecordImpl).frbInternalSseEncode(
        move: true,
      ),
      serializer,
    );
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString(
    CoreResultString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultStringImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString(
    CoreResultVecString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultVecStringImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
    EntityRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EntityRecordImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
    ViewDescriptor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ViewDescriptorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
    CoreResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
    CoreResultEntityRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultEntityRecordImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
    CoreResultListResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultListResultImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
    CoreResultOptionEntityRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultOptionEntityRecordImpl).frbInternalSseEncode(
        move: null,
      ),
      serializer,
    );
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultString(
    CoreResultString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultStringImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultVecString(
    CoreResultVecString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreResultVecStringImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
    EntityRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EntityRecordImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
    ViewDescriptor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ViewDescriptorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class CoreResultEntityRecordImpl extends RustOpaque
    implements CoreResultEntityRecord {
  // Not to be used by end users
  CoreResultEntityRecordImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultEntityRecordImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: GenUiCore
        .instance.api.rust_arc_increment_strong_count_CoreResultEntityRecord,
    rustArcDecrementStrongCount: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultEntityRecord,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultEntityRecordPtr,
  );
}

@sealed
class CoreResultImpl extends RustOpaque implements CoreResult {
  // Not to be used by end users
  CoreResultImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_CoreResult,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreResult,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreResultPtr,
  );
}

@sealed
class CoreResultListResultImpl extends RustOpaque
    implements CoreResultListResult {
  // Not to be used by end users
  CoreResultListResultImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultListResultImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: GenUiCore
        .instance.api.rust_arc_increment_strong_count_CoreResultListResult,
    rustArcDecrementStrongCount: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultListResult,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultListResultPtr,
  );
}

@sealed
class CoreResultOptionEntityRecordImpl extends RustOpaque
    implements CoreResultOptionEntityRecord {
  // Not to be used by end users
  CoreResultOptionEntityRecordImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultOptionEntityRecordImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: GenUiCore.instance.api
        .rust_arc_increment_strong_count_CoreResultOptionEntityRecord,
    rustArcDecrementStrongCount: GenUiCore.instance.api
        .rust_arc_decrement_strong_count_CoreResultOptionEntityRecord,
    rustArcDecrementStrongCountPtr: GenUiCore.instance.api
        .rust_arc_decrement_strong_count_CoreResultOptionEntityRecordPtr,
  );
}

@sealed
class CoreResultStringImpl extends RustOpaque implements CoreResultString {
  // Not to be used by end users
  CoreResultStringImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultStringImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_CoreResultString,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreResultString,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultStringPtr,
  );
}

@sealed
class CoreResultVecStringImpl extends RustOpaque
    implements CoreResultVecString {
  // Not to be used by end users
  CoreResultVecStringImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultVecStringImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: GenUiCore
        .instance.api.rust_arc_increment_strong_count_CoreResultVecString,
    rustArcDecrementStrongCount: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultVecString,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultVecStringPtr,
  );
}

@sealed
class EntityRecordImpl extends RustOpaque implements EntityRecord {
  // Not to be used by end users
  EntityRecordImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  EntityRecordImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_EntityRecord,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_EntityRecord,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_EntityRecordPtr,
  );
}

@sealed
class ViewDescriptorImpl extends RustOpaque implements ViewDescriptor {
  // Not to be used by end users
  ViewDescriptorImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ViewDescriptorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_ViewDescriptor,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_ViewDescriptor,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_ViewDescriptorPtr,
  );
}
