// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chat.dart';
import 'api/entity.dart';
import 'api/streams.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class GenUiCore
    extends BaseEntrypoint<GenUiCoreApi, GenUiCoreApiImpl, GenUiCoreWire> {
  @internal
  static final instance = GenUiCore._();

  GenUiCore._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    GenUiCoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required GenUiCoreApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<GenUiCoreApiImpl, GenUiCoreWire> get apiImplConstructor =>
      GenUiCoreApiImpl.new;

  @override
  WireConstructor<GenUiCoreWire> get wireConstructor =>
      GenUiCoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitCore();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 618846197;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'gen_ui_ffi',
    ioDirectory: '../rust/crates/gen_ui_ffi/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class GenUiCoreApi extends BaseApi {
  Stream<String> crateApiStreamsChatEvents({required String runId});

  Future<String> crateApiChatChatSend(
      {required String threadId, required String message});

  Stream<ChangeEvent> crateApiStreamsEntityChanges();

  Future<CoreResultEntityRecord> crateApiEntityEntityCreate(
      {required EntityRecord record});

  Future<CoreResult> crateApiEntityEntityDelete(
      {required String entityType, required String id});

  Future<CoreResultOptionEntityRecord> crateApiEntityEntityGet(
      {required String entityType, required String id});

  Future<CoreResultListResult> crateApiEntityEntityList(
      {required ViewDescriptor view});

  Future<CoreResultEntityRecord> crateApiEntityEntityUpdate(
      {required EntityRecord record});

  Future<List<String>> crateApiChatGraphExpand(
      {required String entityId, required int depth});

  Future<void> crateApiInitCore({BigInt? workerThreads});

  Future<List<String>> crateApiChatMemorySearch(
      {required String query, required int k});

  Stream<SyncStatus> crateApiStreamsSyncStatus();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ChangeEvent;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ChangeEvent;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ChangeEventPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreError;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CoreErrorPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResult;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResult;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CoreResultPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultEntityRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CoreResultEntityRecordPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultListResult;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultListResult;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CoreResultListResultPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultOptionEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultOptionEntityRecord;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CoreResultOptionEntityRecordPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_EntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_EntityRecord;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_EntityRecordPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_SyncStatus;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_SyncStatus;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SyncStatusPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ViewDescriptor;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ViewDescriptor;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ViewDescriptorPtr;
}

class GenUiCoreApiImpl extends GenUiCoreApiImplPlatform
    implements GenUiCoreApi {
  GenUiCoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<String> crateApiStreamsChatEvents({required String runId}) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(runId, serializer);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer,
                funcId: 1, port: port_);
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiStreamsChatEventsConstMeta,
          argValues: [runId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamsChatEventsConstMeta => const TaskConstMeta(
        debugName: 'chat_events',
        argNames: ['runId', 'sink'],
      );

  @override
  Future<String> crateApiChatChatSend(
      {required String threadId, required String message}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(threadId, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 2, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiChatChatSendConstMeta,
        argValues: [threadId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatSendConstMeta => const TaskConstMeta(
        debugName: 'chat_send',
        argNames: ['threadId', 'message'],
      );

  @override
  Stream<ChangeEvent> crateApiStreamsEntityChanges() {
    final sink = RustStreamSink<ChangeEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent_Sse(
                sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer,
                funcId: 3, port: port_);
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiStreamsEntityChangesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamsEntityChangesConstMeta =>
      const TaskConstMeta(
        debugName: 'entity_changes',
        argNames: ['sink'],
      );

  @override
  Future<CoreResultEntityRecord> crateApiEntityEntityCreate(
      {required EntityRecord record}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
              record, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 4, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityCreateConstMeta,
        argValues: [record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityCreateConstMeta => const TaskConstMeta(
        debugName: 'entity_create',
        argNames: ['record'],
      );

  @override
  Future<CoreResult> crateApiEntityEntityDelete(
      {required String entityType, required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityType, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 5, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityDeleteConstMeta,
        argValues: [entityType, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityDeleteConstMeta => const TaskConstMeta(
        debugName: 'entity_delete',
        argNames: ['entityType', 'id'],
      );

  @override
  Future<CoreResultOptionEntityRecord> crateApiEntityEntityGet(
      {required String entityType, required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityType, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 6, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityGetConstMeta,
        argValues: [entityType, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityGetConstMeta => const TaskConstMeta(
        debugName: 'entity_get',
        argNames: ['entityType', 'id'],
      );

  @override
  Future<CoreResultListResult> crateApiEntityEntityList(
      {required ViewDescriptor view}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
              view, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 7, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityListConstMeta,
        argValues: [view],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityListConstMeta => const TaskConstMeta(
        debugName: 'entity_list',
        argNames: ['view'],
      );

  @override
  Future<CoreResultEntityRecord> crateApiEntityEntityUpdate(
      {required EntityRecord record}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
              record, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 8, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntityEntityUpdateConstMeta,
        argValues: [record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityUpdateConstMeta => const TaskConstMeta(
        debugName: 'entity_update',
        argNames: ['record'],
      );

  @override
  Future<List<String>> crateApiChatGraphExpand(
      {required String entityId, required int depth}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityId, serializer);
          sse_encode_u_32(depth, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 9, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiChatGraphExpandConstMeta,
        argValues: [entityId, depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatGraphExpandConstMeta => const TaskConstMeta(
        debugName: 'graph_expand',
        argNames: ['entityId', 'depth'],
      );

  @override
  Future<void> crateApiInitCore({BigInt? workerThreads}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_usize(workerThreads, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 10, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitCoreConstMeta,
        argValues: [workerThreads],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitCoreConstMeta => const TaskConstMeta(
        debugName: 'init_core',
        argNames: ['workerThreads'],
      );

  @override
  Future<List<String>> crateApiChatMemorySearch(
      {required String query, required int k}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(k, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 11, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiChatMemorySearchConstMeta,
        argValues: [query, k],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatMemorySearchConstMeta => const TaskConstMeta(
        debugName: 'memory_search',
        argNames: ['query', 'k'],
      );

  @override
  Stream<SyncStatus> crateApiStreamsSyncStatus() {
    final sink = RustStreamSink<SyncStatus>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus_Sse(
                sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer,
                funcId: 12, port: port_);
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiStreamsSyncStatusConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamsSyncStatusConstMeta => const TaskConstMeta(
        debugName: 'sync_status',
        argNames: ['sink'],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ChangeEvent => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ChangeEvent => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreError => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreError => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResult => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResult => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultEntityRecord => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultEntityRecord => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultListResult => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultListResult => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CoreResultOptionEntityRecord => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CoreResultOptionEntityRecord => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_EntityRecord => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_EntityRecord => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_SyncStatus => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_SyncStatus => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ViewDescriptor => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ViewDescriptor => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ChangeEvent
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChangeEventImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreError
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResult
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultEntityRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultEntityRecordImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  CoreResultListResult
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultListResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultOptionEntityRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultOptionEntityRecordImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  EntityRecord
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EntityRecordImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SyncStatus
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncStatusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ViewDescriptor
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ViewDescriptorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ChangeEvent
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChangeEventImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreError
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResult
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultEntityRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultEntityRecordImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  CoreResultListResult
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultListResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreResultOptionEntityRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreResultOptionEntityRecordImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  EntityRecord
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EntityRecordImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SyncStatus
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncStatusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ViewDescriptor
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ViewDescriptorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<ChangeEvent>
      dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent_Sse(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SyncStatus>
      dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus_Sse(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ChangeEvent
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChangeEventImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreError
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreErrorImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreResult
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreResultEntityRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultEntityRecordImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreResultListResult
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultListResultImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreResultOptionEntityRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultOptionEntityRecordImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  EntityRecord
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EntityRecordImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  SyncStatus
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SyncStatusImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ViewDescriptor
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ViewDescriptorImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ChangeEvent
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChangeEventImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreError
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreErrorImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreResult
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreResultEntityRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultEntityRecordImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreResultListResult
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultListResultImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CoreResultOptionEntityRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreResultOptionEntityRecordImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  EntityRecord
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EntityRecordImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  SyncStatus
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SyncStatusImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ViewDescriptor
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ViewDescriptorImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<ChangeEvent>
      sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SyncStatus>
      sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
          ChangeEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ChangeEventImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
          CoreError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreErrorImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
          CoreResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreResultImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
          CoreResultEntityRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreResultEntityRecordImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
          CoreResultListResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreResultListResultImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
          CoreResultOptionEntityRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreResultOptionEntityRecordImpl)
            .frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
          EntityRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as EntityRecordImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
          SyncStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SyncStatusImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
          ViewDescriptor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ViewDescriptorImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
          ChangeEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ChangeEventImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
          CoreError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreErrorImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResult(
          CoreResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreResultImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultEntityRecord(
          CoreResultEntityRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreResultEntityRecordImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultListResult(
          CoreResultListResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreResultListResultImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreResultOptionEntityRecord(
          CoreResultOptionEntityRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CoreResultOptionEntityRecordImpl)
            .frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityRecord(
          EntityRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as EntityRecordImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
          SyncStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SyncStatusImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerViewDescriptor(
          ViewDescriptor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ViewDescriptorImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent_Sse(
          RustStreamSink<ChangeEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void
      sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus_Sse(
          RustStreamSink<SyncStatus> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
      BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class ChangeEventImpl extends RustOpaque implements ChangeEvent {
  // Not to be used by end users
  ChangeEventImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ChangeEventImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_ChangeEvent,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_ChangeEvent,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_ChangeEventPtr,
  );
}

@sealed
class CoreErrorImpl extends RustOpaque implements CoreError {
  // Not to be used by end users
  CoreErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_CoreError,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreError,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreErrorPtr,
  );
}

@sealed
class CoreResultEntityRecordImpl extends RustOpaque
    implements CoreResultEntityRecord {
  // Not to be used by end users
  CoreResultEntityRecordImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultEntityRecordImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: GenUiCore
        .instance.api.rust_arc_increment_strong_count_CoreResultEntityRecord,
    rustArcDecrementStrongCount: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultEntityRecord,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultEntityRecordPtr,
  );
}

@sealed
class CoreResultImpl extends RustOpaque implements CoreResult {
  // Not to be used by end users
  CoreResultImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_CoreResult,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreResult,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreResultPtr,
  );
}

@sealed
class CoreResultListResultImpl extends RustOpaque
    implements CoreResultListResult {
  // Not to be used by end users
  CoreResultListResultImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultListResultImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: GenUiCore
        .instance.api.rust_arc_increment_strong_count_CoreResultListResult,
    rustArcDecrementStrongCount: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultListResult,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_CoreResultListResultPtr,
  );
}

@sealed
class CoreResultOptionEntityRecordImpl extends RustOpaque
    implements CoreResultOptionEntityRecord {
  // Not to be used by end users
  CoreResultOptionEntityRecordImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreResultOptionEntityRecordImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: GenUiCore.instance.api
        .rust_arc_increment_strong_count_CoreResultOptionEntityRecord,
    rustArcDecrementStrongCount: GenUiCore.instance.api
        .rust_arc_decrement_strong_count_CoreResultOptionEntityRecord,
    rustArcDecrementStrongCountPtr: GenUiCore.instance.api
        .rust_arc_decrement_strong_count_CoreResultOptionEntityRecordPtr,
  );
}

@sealed
class EntityRecordImpl extends RustOpaque implements EntityRecord {
  // Not to be used by end users
  EntityRecordImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  EntityRecordImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_EntityRecord,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_EntityRecord,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_EntityRecordPtr,
  );
}

@sealed
class SyncStatusImpl extends RustOpaque implements SyncStatus {
  // Not to be used by end users
  SyncStatusImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SyncStatusImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_SyncStatus,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_SyncStatus,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_SyncStatusPtr,
  );
}

@sealed
class ViewDescriptorImpl extends RustOpaque implements ViewDescriptor {
  // Not to be used by end users
  ViewDescriptorImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ViewDescriptorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_ViewDescriptor,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_ViewDescriptor,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance.api.rust_arc_decrement_strong_count_ViewDescriptorPtr,
  );
}
