// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/boot.dart';
import 'api/chat.dart';
import 'api/entity.dart';
import 'api/scribe.dart';
import 'api/streams.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/gen_ui_db_graph.dart';
import 'third_party/gen_ui_types/error.dart';
import 'third_party/gen_ui_types/sync.dart';
import 'third_party/gen_ui_types/transport.dart';
import 'third_party/gen_ui_types/view.dart';

/// Main entrypoint of the Rust API
class GenUiCore
    extends BaseEntrypoint<GenUiCoreApi, GenUiCoreApiImpl, GenUiCoreWire> {
  @internal
  static final instance = GenUiCore._();

  GenUiCore._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    GenUiCoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required GenUiCoreApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<GenUiCoreApiImpl, GenUiCoreWire> get apiImplConstructor =>
      GenUiCoreApiImpl.new;

  @override
  WireConstructor<GenUiCoreWire> get wireConstructor =>
      GenUiCoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitCore();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -861603044;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'gen_ui_ffi',
        ioDirectory: '../rust/crates/gen_ui_ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class GenUiCoreApi extends BaseApi {
  Future<String> genUiDbGraphGraphStoreCreateEntity({
    required GraphStore that,
    required String id,
    required String entityType,
    required String label,
  });

  Future<List<RelatedEntity>> genUiDbGraphGraphStoreGraphExpand({
    required GraphStore that,
    required String entityId,
    required int depth,
  });

  Future<String> genUiDbGraphGraphStoreMemoryIngest({
    required GraphStore that,
    required MemoryRecord record,
  });

  Future<List<MemoryHit>> genUiDbGraphGraphStoreMemorySearch({
    required GraphStore that,
    required String query,
    required BigInt k,
  });

  Future<GraphStore> genUiDbGraphGraphStoreOpen({
    required GraphStoreConfig cfg,
  });

  Future<void> genUiDbGraphGraphStoreRelate({
    required GraphStore that,
    required String from,
    required String to,
    required String rel,
  });

  Future<void> crateApiBootAttachSyncShapes();

  Stream<String> crateApiStreamsChatEvents({required String runId});

  Future<String> crateApiChatChatSend({
    required String threadId,
    required String message,
  });

  Stream<String> crateApiStreamsEntityChanges();

  Future<EntityRecord> crateApiEntityEntityCreate({
    required EntityRecord record,
  });

  Future<void> crateApiEntityEntityDelete({
    required String entityType,
    required String id,
  });

  Future<EntityRecord?> crateApiEntityEntityGet({
    required String entityType,
    required String id,
  });

  Future<ListResult> crateApiEntityEntityList({required ViewDescriptor view});

  Future<EntityRecord> crateApiEntityEntityUpdate({
    required EntityRecord record,
  });

  Future<List<RelatedEntity>> crateApiChatGraphExpand({
    required String entityId,
    required int depth,
  });

  Future<void> crateApiInitCore({BigInt? workerThreads});

  Future<void> crateApiBootLoadSeeds();

  Future<String> crateApiChatMemoryIngest({required String text});

  Future<List<MemoryHit>> crateApiChatMemorySearch({
    required String query,
    required int k,
  });

  Future<void> crateApiBootRunMigrations({required String dataDir});

  Future<void> crateApiScribeScribeStart();

  Future<String> crateApiScribeScribeStop();

  Stream<String> crateApiStreamsSyncStatus();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ChangeEvent;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ChangeEvent;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ChangeEventPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CoreError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CoreError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CoreErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GraphError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GraphError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_GraphErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GraphStore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GraphStore;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_GraphStorePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GraphStoreConfig;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GraphStoreConfig;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GraphStoreConfigPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SyncStatus;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SyncStatus;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SyncStatusPtr;
}

class GenUiCoreApiImpl extends GenUiCoreApiImplPlatform
    implements GenUiCoreApi {
  GenUiCoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> genUiDbGraphGraphStoreCreateEntity({
    required GraphStore that,
    required String id,
    required String entityType,
    required String label,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          sse_encode_String(entityType, serializer);
          sse_encode_String(label, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError,
        ),
        constMeta: kGenUiDbGraphGraphStoreCreateEntityConstMeta,
        argValues: [that, id, entityType, label],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kGenUiDbGraphGraphStoreCreateEntityConstMeta =>
      const TaskConstMeta(
        debugName: 'GraphStore_create_entity',
        argNames: ['that', 'id', 'entityType', 'label'],
      );

  @override
  Future<List<RelatedEntity>> genUiDbGraphGraphStoreGraphExpand({
    required GraphStore that,
    required String entityId,
    required int depth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
            that,
            serializer,
          );
          sse_encode_String(entityId, serializer);
          sse_encode_u_8(depth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_related_entity,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError,
        ),
        constMeta: kGenUiDbGraphGraphStoreGraphExpandConstMeta,
        argValues: [that, entityId, depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kGenUiDbGraphGraphStoreGraphExpandConstMeta =>
      const TaskConstMeta(
        debugName: 'GraphStore_graph_expand',
        argNames: ['that', 'entityId', 'depth'],
      );

  @override
  Future<String> genUiDbGraphGraphStoreMemoryIngest({
    required GraphStore that,
    required MemoryRecord record,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
            that,
            serializer,
          );
          sse_encode_box_autoadd_memory_record(record, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError,
        ),
        constMeta: kGenUiDbGraphGraphStoreMemoryIngestConstMeta,
        argValues: [that, record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kGenUiDbGraphGraphStoreMemoryIngestConstMeta =>
      const TaskConstMeta(
        debugName: 'GraphStore_memory_ingest',
        argNames: ['that', 'record'],
      );

  @override
  Future<List<MemoryHit>> genUiDbGraphGraphStoreMemorySearch({
    required GraphStore that,
    required String query,
    required BigInt k,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          sse_encode_usize(k, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_memory_hit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError,
        ),
        constMeta: kGenUiDbGraphGraphStoreMemorySearchConstMeta,
        argValues: [that, query, k],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kGenUiDbGraphGraphStoreMemorySearchConstMeta =>
      const TaskConstMeta(
        debugName: 'GraphStore_memory_search',
        argNames: ['that', 'query', 'k'],
      );

  @override
  Future<GraphStore> genUiDbGraphGraphStoreOpen({
    required GraphStoreConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig(
            cfg,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError,
        ),
        constMeta: kGenUiDbGraphGraphStoreOpenConstMeta,
        argValues: [cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kGenUiDbGraphGraphStoreOpenConstMeta =>
      const TaskConstMeta(debugName: 'GraphStore_open', argNames: ['cfg']);

  @override
  Future<void> genUiDbGraphGraphStoreRelate({
    required GraphStore that,
    required String from,
    required String to,
    required String rel,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
            that,
            serializer,
          );
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          sse_encode_String(rel, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError,
        ),
        constMeta: kGenUiDbGraphGraphStoreRelateConstMeta,
        argValues: [that, from, to, rel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kGenUiDbGraphGraphStoreRelateConstMeta =>
      const TaskConstMeta(
        debugName: 'GraphStore_relate',
        argNames: ['that', 'from', 'to', 'rel'],
      );

  @override
  Future<void> crateApiBootAttachSyncShapes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiBootAttachSyncShapesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBootAttachSyncShapesConstMeta =>
      const TaskConstMeta(debugName: 'attach_sync_shapes', argNames: []);

  @override
  Stream<String> crateApiStreamsChatEvents({required String runId}) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(runId, serializer);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiStreamsChatEventsConstMeta,
          argValues: [runId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamsChatEventsConstMeta => const TaskConstMeta(
    debugName: 'chat_events',
    argNames: ['runId', 'sink'],
  );

  @override
  Future<String> crateApiChatChatSend({
    required String threadId,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(threadId, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiChatChatSendConstMeta,
        argValues: [threadId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatSendConstMeta => const TaskConstMeta(
    debugName: 'chat_send',
    argNames: ['threadId', 'message'],
  );

  @override
  Stream<String> crateApiStreamsEntityChanges() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiStreamsEntityChangesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamsEntityChangesConstMeta =>
      const TaskConstMeta(debugName: 'entity_changes', argNames: ['sink']);

  @override
  Future<EntityRecord> crateApiEntityEntityCreate({
    required EntityRecord record,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_entity_record(record, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entity_record,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiEntityEntityCreateConstMeta,
        argValues: [record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityCreateConstMeta =>
      const TaskConstMeta(debugName: 'entity_create', argNames: ['record']);

  @override
  Future<void> crateApiEntityEntityDelete({
    required String entityType,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityType, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiEntityEntityDeleteConstMeta,
        argValues: [entityType, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityDeleteConstMeta => const TaskConstMeta(
    debugName: 'entity_delete',
    argNames: ['entityType', 'id'],
  );

  @override
  Future<EntityRecord?> crateApiEntityEntityGet({
    required String entityType,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityType, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_entity_record,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiEntityEntityGetConstMeta,
        argValues: [entityType, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityGetConstMeta => const TaskConstMeta(
    debugName: 'entity_get',
    argNames: ['entityType', 'id'],
  );

  @override
  Future<ListResult> crateApiEntityEntityList({required ViewDescriptor view}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_view_descriptor(view, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiEntityEntityListConstMeta,
        argValues: [view],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityListConstMeta =>
      const TaskConstMeta(debugName: 'entity_list', argNames: ['view']);

  @override
  Future<EntityRecord> crateApiEntityEntityUpdate({
    required EntityRecord record,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_entity_record(record, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entity_record,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiEntityEntityUpdateConstMeta,
        argValues: [record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntityEntityUpdateConstMeta =>
      const TaskConstMeta(debugName: 'entity_update', argNames: ['record']);

  @override
  Future<List<RelatedEntity>> crateApiChatGraphExpand({
    required String entityId,
    required int depth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityId, serializer);
          sse_encode_u_32(depth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_related_entity,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiChatGraphExpandConstMeta,
        argValues: [entityId, depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatGraphExpandConstMeta => const TaskConstMeta(
    debugName: 'graph_expand',
    argNames: ['entityId', 'depth'],
  );

  @override
  Future<void> crateApiInitCore({BigInt? workerThreads}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_usize(workerThreads, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitCoreConstMeta,
        argValues: [workerThreads],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitCoreConstMeta =>
      const TaskConstMeta(debugName: 'init_core', argNames: ['workerThreads']);

  @override
  Future<void> crateApiBootLoadSeeds() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiBootLoadSeedsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBootLoadSeedsConstMeta =>
      const TaskConstMeta(debugName: 'load_seeds', argNames: []);

  @override
  Future<String> crateApiChatMemoryIngest({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiChatMemoryIngestConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatMemoryIngestConstMeta =>
      const TaskConstMeta(debugName: 'memory_ingest', argNames: ['text']);

  @override
  Future<List<MemoryHit>> crateApiChatMemorySearch({
    required String query,
    required int k,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(k, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_memory_hit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiChatMemorySearchConstMeta,
        argValues: [query, k],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatMemorySearchConstMeta =>
      const TaskConstMeta(debugName: 'memory_search', argNames: ['query', 'k']);

  @override
  Future<void> crateApiBootRunMigrations({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiBootRunMigrationsConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBootRunMigrationsConstMeta =>
      const TaskConstMeta(debugName: 'run_migrations', argNames: ['dataDir']);

  @override
  Future<void> crateApiScribeScribeStart() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiScribeScribeStartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScribeScribeStartConstMeta =>
      const TaskConstMeta(debugName: 'scribe_start', argNames: []);

  @override
  Future<String> crateApiScribeScribeStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError,
        ),
        constMeta: kCrateApiScribeScribeStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScribeScribeStopConstMeta =>
      const TaskConstMeta(debugName: 'scribe_stop', argNames: []);

  @override
  Stream<String> crateApiStreamsSyncStatus() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 25,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiStreamsSyncStatusConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamsSyncStatusConstMeta =>
      const TaskConstMeta(debugName: 'sync_status', argNames: ['sink']);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ChangeEvent => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ChangeEvent => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CoreError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CoreError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GraphError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GraphError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GraphStore => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GraphStore => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GraphStoreConfig => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GraphStoreConfig => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SyncStatus => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SyncStatus => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ChangeEvent
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChangeEventImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GraphError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GraphErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GraphStore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GraphStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GraphStoreConfig
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GraphStoreConfigImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SyncStatus
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncStatusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GraphStore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GraphStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ChangeEvent
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChangeEventImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CoreError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GraphError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GraphErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GraphStore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GraphStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GraphStoreConfig
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GraphStoreConfigImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SyncStatus
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncStatusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  SyncTransport dco_decode_TraitDef_SyncTransport(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EntityRecord dco_decode_box_autoadd_entity_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_entity_record(raw);
  }

  @protected
  MemoryRecord dco_decode_box_autoadd_memory_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_memory_record(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  ViewDescriptor dco_decode_box_autoadd_view_descriptor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_view_descriptor(raw);
  }

  @protected
  EntityRecord dco_decode_entity_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EntityRecord(
      id: dco_decode_String(arr[0]),
      entityType: dco_decode_String(arr[1]),
      dataJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FilterOp dco_decode_filter_op(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FilterOp.values[raw as int];
  }

  @protected
  FilterSpec dco_decode_filter_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FilterSpec(
      field: dco_decode_String(arr[0]),
      op: dco_decode_filter_op(arr[1]),
      valueJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<EntityRecord> dco_decode_list_entity_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entity_record).toList();
  }

  @protected
  List<FilterSpec> dco_decode_list_filter_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_filter_spec).toList();
  }

  @protected
  List<MemoryHit> dco_decode_list_memory_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_memory_hit).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RelatedEntity> dco_decode_list_related_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_related_entity).toList();
  }

  @protected
  ListResult dco_decode_list_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ListResult(
      items: dco_decode_list_entity_record(arr[0]),
      nextCursor: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  List<SortSpec> dco_decode_list_sort_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sort_spec).toList();
  }

  @protected
  MemoryHit dco_decode_memory_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MemoryHit(
      id: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      score: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  MemoryRecord dco_decode_memory_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MemoryRecord(
      id: dco_decode_opt_String(arr[0]),
      text: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      entity: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  EntityRecord? dco_decode_opt_box_autoadd_entity_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_entity_record(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  RelatedEntity dco_decode_related_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RelatedEntity(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      entityType: dco_decode_String(arr[2]),
      score: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  SortSpec dco_decode_sort_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SortSpec(
      field: dco_decode_String(arr[0]),
      descending: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ViewDescriptor dco_decode_view_descriptor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ViewDescriptor(
      entityType: dco_decode_String(arr[0]),
      filters: dco_decode_list_filter_spec(arr[1]),
      sorts: dco_decode_list_sort_spec(arr[2]),
      limit: dco_decode_opt_box_autoadd_u_32(arr[3]),
      cursor: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ChangeEvent
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChangeEventImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GraphError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GraphErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GraphStore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GraphStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GraphStoreConfig
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GraphStoreConfigImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SyncStatus
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SyncStatusImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GraphStore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GraphStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ChangeEvent
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChangeEventImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CoreError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GraphError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GraphErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GraphStore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GraphStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GraphStoreConfig
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GraphStoreConfigImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SyncStatus
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SyncStatusImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EntityRecord sse_decode_box_autoadd_entity_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_entity_record(deserializer));
  }

  @protected
  MemoryRecord sse_decode_box_autoadd_memory_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_memory_record(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  ViewDescriptor sse_decode_box_autoadd_view_descriptor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_view_descriptor(deserializer));
  }

  @protected
  EntityRecord sse_decode_entity_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_entityType = sse_decode_String(deserializer);
    var var_dataJson = sse_decode_String(deserializer);
    return EntityRecord(
      id: var_id,
      entityType: var_entityType,
      dataJson: var_dataJson,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FilterOp sse_decode_filter_op(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FilterOp.values[inner];
  }

  @protected
  FilterSpec sse_decode_filter_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field = sse_decode_String(deserializer);
    var var_op = sse_decode_filter_op(deserializer);
    var var_valueJson = sse_decode_String(deserializer);
    return FilterSpec(field: var_field, op: var_op, valueJson: var_valueJson);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<EntityRecord> sse_decode_list_entity_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntityRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entity_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<FilterSpec> sse_decode_list_filter_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FilterSpec>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_filter_spec(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemoryHit> sse_decode_list_memory_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemoryHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_memory_hit(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RelatedEntity> sse_decode_list_related_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RelatedEntity>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_related_entity(deserializer));
    }
    return ans_;
  }

  @protected
  ListResult sse_decode_list_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_entity_record(deserializer);
    var var_nextCursor = sse_decode_opt_String(deserializer);
    return ListResult(items: var_items, nextCursor: var_nextCursor);
  }

  @protected
  List<SortSpec> sse_decode_list_sort_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SortSpec>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sort_spec(deserializer));
    }
    return ans_;
  }

  @protected
  MemoryHit sse_decode_memory_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return MemoryHit(
      id: var_id,
      text: var_text,
      kind: var_kind,
      score: var_score,
    );
  }

  @protected
  MemoryRecord sse_decode_memory_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_entity = sse_decode_opt_String(deserializer);
    return MemoryRecord(
      id: var_id,
      text: var_text,
      kind: var_kind,
      entity: var_entity,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  EntityRecord? sse_decode_opt_box_autoadd_entity_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_entity_record(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RelatedEntity sse_decode_related_entity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_entityType = sse_decode_String(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return RelatedEntity(
      id: var_id,
      label: var_label,
      entityType: var_entityType,
      score: var_score,
    );
  }

  @protected
  SortSpec sse_decode_sort_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field = sse_decode_String(deserializer);
    var var_descending = sse_decode_bool(deserializer);
    return SortSpec(field: var_field, descending: var_descending);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  ViewDescriptor sse_decode_view_descriptor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entityType = sse_decode_String(deserializer);
    var var_filters = sse_decode_list_filter_spec(deserializer);
    var var_sorts = sse_decode_list_sort_spec(deserializer);
    var var_limit = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_cursor = sse_decode_opt_String(deserializer);
    return ViewDescriptor(
      entityType: var_entityType,
      filters: var_filters,
      sorts: var_sorts,
      limit: var_limit,
      cursor: var_cursor,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
    ChangeEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ChangeEventImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
    CoreError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError(
    GraphError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GraphErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    GraphStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GraphStoreImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig(
    GraphStoreConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GraphStoreConfigImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    SyncStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SyncStatusImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    GraphStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GraphStoreImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChangeEvent(
    ChangeEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ChangeEventImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCoreError(
    CoreError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphError(
    GraphError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GraphErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStore(
    GraphStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GraphStoreImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGraphStoreConfig(
    GraphStoreConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GraphStoreConfigImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    SyncStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SyncStatusImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_entity_record(
    EntityRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_entity_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_memory_record(
    MemoryRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_memory_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_view_descriptor(
    ViewDescriptor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_view_descriptor(self, serializer);
  }

  @protected
  void sse_encode_entity_record(EntityRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.entityType, serializer);
    sse_encode_String(self.dataJson, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_filter_op(FilterOp self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_filter_spec(FilterSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.field, serializer);
    sse_encode_filter_op(self.op, serializer);
    sse_encode_String(self.valueJson, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_entity_record(
    List<EntityRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entity_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_filter_spec(
    List<FilterSpec> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_filter_spec(item, serializer);
    }
  }

  @protected
  void sse_encode_list_memory_hit(
    List<MemoryHit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_memory_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_related_entity(
    List<RelatedEntity> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_related_entity(item, serializer);
    }
  }

  @protected
  void sse_encode_list_result(ListResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_entity_record(self.items, serializer);
    sse_encode_opt_String(self.nextCursor, serializer);
  }

  @protected
  void sse_encode_list_sort_spec(
    List<SortSpec> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sort_spec(item, serializer);
    }
  }

  @protected
  void sse_encode_memory_hit(MemoryHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_memory_record(MemoryRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.id, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.entity, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_entity_record(
    EntityRecord? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_entity_record(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_related_entity(RelatedEntity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.entityType, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_sort_spec(SortSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.field, serializer);
    sse_encode_bool(self.descending, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_view_descriptor(
    ViewDescriptor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.entityType, serializer);
    sse_encode_list_filter_spec(self.filters, serializer);
    sse_encode_list_sort_spec(self.sorts, serializer);
    sse_encode_opt_box_autoadd_u_32(self.limit, serializer);
    sse_encode_opt_String(self.cursor, serializer);
  }
}

@sealed
class ChangeEventImpl extends RustOpaque implements ChangeEvent {
  // Not to be used by end users
  ChangeEventImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ChangeEventImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_ChangeEvent,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_ChangeEvent,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_ChangeEventPtr,
  );
}

@sealed
class CoreErrorImpl extends RustOpaque implements CoreError {
  // Not to be used by end users
  CoreErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_CoreError,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreError,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_CoreErrorPtr,
  );
}

@sealed
class GraphErrorImpl extends RustOpaque implements GraphError {
  // Not to be used by end users
  GraphErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GraphErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_GraphError,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_GraphError,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_GraphErrorPtr,
  );
}

@sealed
class GraphStoreConfigImpl extends RustOpaque implements GraphStoreConfig {
  // Not to be used by end users
  GraphStoreConfigImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GraphStoreConfigImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_GraphStoreConfig,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_GraphStoreConfig,
    rustArcDecrementStrongCountPtr: GenUiCore
        .instance
        .api
        .rust_arc_decrement_strong_count_GraphStoreConfigPtr,
  );
}

@sealed
class GraphStoreImpl extends RustOpaque implements GraphStore {
  // Not to be used by end users
  GraphStoreImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GraphStoreImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_GraphStore,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_GraphStore,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_GraphStorePtr,
  );

  /// INTENT: create (or upsert) a graph entity node. `id` is the record key
  /// (e.g. `project_x`); `label`/`entity_type` are indexed graph metadata.
  Future<String> createEntity({
    required String id,
    required String entityType,
    required String label,
  }) => GenUiCore.instance.api.genUiDbGraphGraphStoreCreateEntity(
    that: this,
    id: id,
    entityType: entityType,
    label: label,
  );

  /// INTENT: expand the graph outward from `entity_id` up to `depth` RELATE hops,
  /// fusing per-depth neighbour lists with Rust RRF (nearer hops rank higher).
  Future<List<RelatedEntity>> graphExpand({
    required String entityId,
    required int depth,
  }) => GenUiCore.instance.api.genUiDbGraphGraphStoreGraphExpand(
    that: this,
    entityId: entityId,
    depth: depth,
  );

  /// INTENT: ingest a memory. Embeds `text`, stores row + vector, returns the id.
  Future<String> memoryIngest({required MemoryRecord record}) => GenUiCore
      .instance
      .api
      .genUiDbGraphGraphStoreMemoryIngest(that: this, record: record);

  /// INTENT: hybrid semantic + lexical search. Embeds `query`, runs the vector
  /// and BM25 lanes, fuses them with native `search::rrf`, returns top-`k`.
  Future<List<MemoryHit>> memorySearch({
    required String query,
    required BigInt k,
  }) => GenUiCore.instance.api.genUiDbGraphGraphStoreMemorySearch(
    that: this,
    query: query,
    k: k,
  );

  /// INTENT: create a directed RELATE edge `from -> to` with a relation label.
  /// Edges are what `graph_expand` traverses.
  Future<void> relate({
    required String from,
    required String to,
    required String rel,
  }) => GenUiCore.instance.api.genUiDbGraphGraphStoreRelate(
    that: this,
    from: from,
    to: to,
    rel: rel,
  );
}

@sealed
class SyncStatusImpl extends RustOpaque implements SyncStatus {
  // Not to be used by end users
  SyncStatusImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SyncStatusImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        GenUiCore.instance.api.rust_arc_increment_strong_count_SyncStatus,
    rustArcDecrementStrongCount:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_SyncStatus,
    rustArcDecrementStrongCountPtr:
        GenUiCore.instance.api.rust_arc_decrement_strong_count_SyncStatusPtr,
  );
}
