#!/usr/bin/env bash
# scripts/scaffold-hybrid.sh
# Scaffold a complete hybrid project: Flutter mobile + Tauri desktop + shared Rust core
# Usage: bash scripts/scaffold-hybrid.sh <project-name> [--org com.example] [--uar embedded|external]

set -euo pipefail

# Resolve to an ABSOLUTE path before any `cd` — every subsequent step in this script
# cd's into the new project directory, so a relative `$(dirname "$0")` (e.g. "scripts")
# would silently resolve against the WRONG directory after that cd (this was a real,
# previously-undiscovered bug: it made every downstream `bash "$(dirname "$0")/foo.sh"`
# call look for scripts inside the freshly-scaffolded project instead of this repo).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Version pins and platform baselines come from versions.toml — never inline a
# literal here. Sourced before the first `cd` so the relative path still resolves.
source "$SCRIPT_DIR/lib-versions.sh"

PROJECT="${1:-my-hybrid-app}"
ORG="${2:---org}"; ORG="${3:-ai.prometheusags}"
UAR_MODE="${5:-embedded}"
# PROJECT may be a path (e.g. "apps/my-app"); the leaf name is what downstream
# scaffolds use for package/app naming (Dart snake_case, npm names, etc.) — passing
# the full path broke a sed substitution once "/" appeared in a "name" value.
APP_NAME="$(basename "$PROJECT")"

CYAN='\033[0;36m'; GREEN='\033[0;32m'; NC='\033[0m'
step() { echo -e "\n${CYAN}── $1${NC}"; }
ok()   { echo -e "${GREEN}  ✓${NC} $1"; }

# Verify environment first
bash "$SCRIPT_DIR/check-env.sh" || { echo "Fix environment issues first."; exit 1; }

step "Creating workspace: $PROJECT"
mkdir -p "$PROJECT"/{rust,mobile,desktop,docs}
cd "$PROJECT"

# ── Scaffold the layered gen_ui Rust workspace ─────────────────────────────
# The workspace Cargo.toml (root, profiles, workspace.dependencies) and all 12
# crates are emitted by scaffold-rust-core.sh — it owns the layered layout,
# compile-speed profiles (panic=unwind for FFI, wasm-release), and .cargo/bacon
# config. Do NOT inline a workspace manifest here; that duplicated the source of
# truth and drifted (old single-crate layout, surrealdb 2.0, panic=abort bug).
step "Scaffolding layered gen_ui workspace"
bash "$SCRIPT_DIR/scaffold-rust-core.sh" "rust" "$UAR_MODE"
ok "gen_ui workspace scaffolded (12 crates, layered)"

# ── Scaffold publishable packages (C-007) ──────────────────────────────────
# Emit path dependencies before either application surface so their first
# package-manager run is real and code generation can complete immediately.
step "Scaffolding publishable packages"
bash "$SCRIPT_DIR/scaffold-packages.sh" "."
ok "Package skeletons scaffolded (npm + pub.dev)"

# ── Scaffold Flutter app ───────────────────────────────────────────────────
step "Scaffolding Flutter mobile app"
bash "$SCRIPT_DIR/scaffold-flutter.sh" "mobile" "$APP_NAME"
ok "Flutter app scaffolded in mobile/"

# ── Scaffold Tauri app ─────────────────────────────────────────────────────
step "Scaffolding Tauri desktop/web app"
bash "$SCRIPT_DIR/scaffold-tauri.sh" "desktop" "$APP_NAME"
ok "Tauri desktop/web app scaffolded in desktop/"

# ── Project-local UI/UX skills + activation hook (C-009) ───────────────────
# Emits templates/project-skills into all six harness skill directories plus a
# Claude UserPromptSubmit activation hook (raises skill hit-rate ~50% -> ~84-100%).
step "Installing project-local UI/UX skills"
bash "$SCRIPT_DIR/add-project-skills.sh" "." || echo "  (skills step skipped)"

# ── Copy documentation ─────────────────────────────────────────────────────
step "Copying architecture documentation"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
if [[ -f "$SKILL_DIR/docs/tj-arch-mob-001.html" ]]; then
  cp "$SKILL_DIR/docs/tj-arch-mob-001.html" "docs/"
  ok "Architecture standard (TJ-ARCH-MOB-001) copied to docs/"
fi

# ── Prometheus Base Rules (binding for all agents working in the project) ──
# Rule propagation is mandatory: every generated project carries the canonical
# 40-rule file, and its agent-instruction files declare it binding.
if [[ -f "$SKILL_DIR/AGENT_BASE_RULES.md" ]]; then
  cp "$SKILL_DIR/AGENT_BASE_RULES.md" .
  cat > CLAUDE.md << 'RULESEOF'
# CLAUDE.md

This project was generated by the TJ-ARCH-MOB-001 hybrid-mobile-architecture skill.

## Binding rules

- **[AGENT_BASE_RULES.md](AGENT_BASE_RULES.md)** — the 40 Prometheus Base Rules. All
  agents (Claude Code, Codex, OpenCode, Kimi, Gemini, Roo, Cline, etc.) working in this
  project MUST follow them: think before coding, simplicity first, surgical changes,
  strict layering (UI → Hooks → Stores → Services → External), feature-based clean
  architecture, strong typing, verified dependency versions, auditable actions.
- **docs/tj-arch-mob-001.html** — the architecture standard. Platform selection and
  the gen_ui_core invariant (all networking/LLM/persistence in Rust) are non-negotiable.
- Project-local skills in `.claude/skills/`, `.codex/skills/`, `.opencode/skills/`,
  `.kimi/skills/`, `.agents/skills/`, and `.kimi-code/skills/` operate under the same rules.

## Layering (Rule 16 — enforced by audit.sh)

Flutter: Widget → @riverpod provider → Repository → FFI (Rust core)
React:   Component → Hook → Store → invoke()/API (stores are the ONLY invoke() layer)

## React UI and entity state

- Always use `@prometheus-ags/prometheus-entity-management` 3.x for normalized server, async, and entity state. Do not add TanStack Query.
- Prefer shadcn/ui components over raw HTML controls for consistent behavior and branding.
- Flutter uses the corresponding shared tokens and shadcn_flutter components.
- Assistant UI owns the React chat thread, composer, thread list, streaming lifecycle, attachments, and message actions.
- Persist conversations as Prometheus Entity Management 3.x entities: PGlite on web and pglite-oxide through typed Rust commands on Tauri. Keep only transient interaction state in Zustand.
- Flat 2.0 is mandatory: no visible borders, divider lines, decorative outlines, or layout shadows. Regions differ only by background color in light and dark themes.

## Local inference is per-device

There is no single "mobile" engine. Every lane sits behind the same
`InferenceProvider` seam, so surface code is identical — only the backend differs:

| Surface | Engine |
|---------|--------|
| Desktop | @INFERENCE_DESKTOP@ |
| Android | @INFERENCE_ANDROID@ |
| iOS     | @INFERENCE_IOS@ |
| Web     | @INFERENCE_WEB@ |

Agent runs select one of three lanes: `cloud`, `local`, or `uar`. Never add a
fourth lane string without updating the Rust validator and both surfaces.

## Platform support policy

- Optimize for current-generation phones and high-impact capabilities. Legacy-device
  compatibility is not a product constraint. Raise the minimum supported Dart, Flutter,
  Android, and iOS versions whenever a modern dependency, security improvement, native
  capability, or materially better UX requires it; document each increase and verify the
  resulting production build on a current physical device.
- Current baselines live in `versions.toml` `[platform]` and `docs/platform-support.md`.
  Changing one means changing all of: the manifests, both files, and a fresh
  physical-device verification record.
RULESEOF

  # The heredoc above is QUOTED so backticks and markdown survive verbatim;
  # substitute the per-device engine names afterwards.
  sed -i.bak \
    -e "s|@INFERENCE_DESKTOP@|${INFERENCE_DESKTOP}|" \
    -e "s|@INFERENCE_ANDROID@|${INFERENCE_ANDROID}|" \
    -e "s|@INFERENCE_IOS@|${INFERENCE_IOS}|" \
    -e "s|@INFERENCE_WEB@|${INFERENCE_WEB}|" \
    CLAUDE.md && rm -f CLAUDE.md.bak

  # AGENTS.md is the cross-harness twin of CLAUDE.md, NOT a byte-copy of it:
  # a literal `cp` leaves the "# CLAUDE.md" heading in place, so every non-Claude
  # harness opens a file that announces itself as another tool's config.
  {
    echo "# AGENTS.md"
    echo ""
    echo "Cross-harness agent instructions (Codex, OpenCode, Kimi, Gemini, Roo, Cline)."
    echo "Claude Code reads the identical rules from CLAUDE.md."
    echo ""
    sed '1{/^# CLAUDE\.md$/d;}' CLAUDE.md | sed '1{/^$/d;}'
  } > AGENTS.md
  ok "AGENT_BASE_RULES.md + CLAUDE.md/AGENTS.md (rules declared binding)"
fi

# ── Platform support policy doc ───────────────────────────────────────────
# The policy needs a home that survives independently of CLAUDE.md, because a
# baseline bump must be auditable: which versions, verified on which device, when.
step "Writing docs/platform-support.md"
cat > docs/platform-support.md << PLATEOF
# Platform support policy

This project prioritizes high-impact native capabilities on current-generation
phones over legacy device coverage. Minimum toolchain and OS versions may be
raised whenever a current stable dependency, security control, accessibility
feature, media capability, or materially better UX requires it.

Current baseline (source of truth: \`versions.toml\`):

- Dart: ${DART_MIN} or newer
- Flutter: ${FLUTTER_VERSION} or newer
- Rust: ${RUST_VERSION}
- Android: API ${ANDROID_MIN_SDK} (Android 10) or newer
- Android native ABI: ${ANDROID_ABI}
- iOS: ${IOS_DEPLOYMENT_TARGET} or newer
- macOS: ${MACOS_DEPLOYMENT_TARGET} or newer

Every baseline change must update the manifests, lockfiles, \`versions.toml\`,
project guidance, and this note. Before release, verify analysis/tests and
install the application on a current physical device; record the Flutter/Dart
versions, Android API level, device model, and verification date below.

## Latest physical-device verification

- Date: _(not yet verified — record the first device run here)_
- Device: _(model, Android API level or iOS version, ABI)_
- Toolchain: Flutter ${FLUTTER_VERSION}, Dart ${DART_MIN}
- Result: _(what was built, installed, launched, and visually confirmed)_

> A generated project starts UNVERIFIED on purpose. Compiling is not evidence
> that the local-inference lanes work: those fail at model load on-device, long
> after every desktop check has passed.
PLATEOF
ok "docs/platform-support.md (baseline + device-verification record)"

# ── Root README ───────────────────────────────────────────────────────────
step "Writing root README"
cat > README.md << READMEEOF
# $PROJECT — Hybrid Mobile + Desktop Application

Built on the [Prometheus AGS Hybrid Mobile Architecture](docs/tj-arch-mob-001.html).

## Structure

\`\`\`
$PROJECT/
├── rust/               ← Shared layered Rust workspace (gen_ui_core + leaves: ffi, tauri-plugin, wasm)
├── mobile/             ← Flutter iOS/Android application (Riverpod, gen_ui widgets)
├── desktop/            ← Tauri macOS/Windows/Linux application (React 19, Zustand, Prometheus Entity Management 3.x, TanStack Router/Table)
├── packages/           ← Publishable npm packages (@prometheus-ags/gen-ui-react, gen-ui-wasm)
├── flutter_packages/   ← Publishable pub.dev packages (gen_ui_flutter FFI plugin, gen_ui_widgets)
└── docs/               ← Architecture documentation
\`\`\`

## Quick start

\`\`\`bash
# Check environment
bash scripts/check-env.sh --install

# Build shared Rust core (Android)
bash scripts/android/build.sh release

# Build shared Rust core (iOS/macOS)
bash scripts/ios/build-xcframework.sh release

# Generate Flutter FFI bindings
flutter_rust_bridge_codegen generate \\
  --rust-input rust/gen_ui_core/src/api.rs \\
  --dart-output mobile/lib/bridge/generated_api.dart

# Run Flutter
cd mobile && flutter run

# Run Tauri desktop
cd desktop && pnpm tauri dev
\`\`\`

## Architecture Standard

See [TJ-ARCH-MOB-001](docs/tj-arch-mob-001.html) for platform selection criteria,
state management standards, and enforcement rules.
READMEEOF
ok "README.md written"

# ── .gitignore ────────────────────────────────────────────────────────────
cat > .gitignore << EOF
# Rust
target/
*.lock

# Flutter
mobile/.dart_tool/
mobile/build/
mobile/.flutter-plugins
mobile/.flutter-plugins-dependencies
mobile/android/app/src/main/jniLibs/
mobile/ios/Frameworks/

# Tauri/Node
desktop/node_modules/
desktop/src-tauri/target/
desktop/dist/

# Publishable packages (C-007)
packages/*/node_modules/
packages/*/dist/
packages/gen-ui-wasm/pkg/
rust/crates/tauri-plugin-gen-ui/guest-js/node_modules/
rust/crates/tauri-plugin-gen-ui/guest-js/dist/
flutter_packages/*/.dart_tool/
flutter_packages/*/build/

# Environment
.env
.env.*
!.env.example
EOF
ok ".gitignore"

echo ""
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ Hybrid project scaffolded: $PROJECT  ${NC}"
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo ""
echo "  Next steps:"
echo "  1. Launch with the bundled local model (no key or account required)"
echo "  2. bash scripts/check-env.sh --install"
echo "  3. Read docs/tj-arch-mob-001.html for architecture decisions"
echo "  4. cd mobile && flutter pub get && flutter run"
echo "  5. cd desktop && pnpm install && pnpm tauri dev"
echo "  6. Optional cloud models are configured through the BYOK Settings UI"
echo ""
