// TJ-ARCH-MOB-001 compliant
//! Tauri 2 plugin build script: generates permission schemas + the guest-side
//! command allowlist from COMMANDS. Keep COMMANDS in sync with the invoke_handler
//! in src/lib.rs.
const COMMANDS: &[&str] = &[
    "chat_send",
    // T8 fix: chat_subscribe was registered in the invoke_handler! (src/lib.rs)
    // but missing here, so it had no autogenerated permission file and no entry
    // in default.toml — Tauri 2's ACL would reject every call at runtime with a
    // capability error even though the command itself compiles and is wired up.
    "chat_subscribe",
    "entity_list",
    "entity_get",
    "entity_create",
    "entity_update",
    "entity_delete",
    "memory_search",
    "graph_expand",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
